#+OPTIONS: toc:nil
#+HTML_HEAD: <link href="../css/solarized-dark.css" rel="stylesheet" />
#+HTML_LINK_HOME: ../index.html
#+TITLE: Chili

2015-10-28

* Ingredients

- 1/2 - 1 lb bacon
- 3 onions
- 5 bell peppers
- 1 whole roasting chicken
- 3-4 cups dry black beans, cooked, with liquid
- 2 big cans (56 oz.) canned tomatoes, with liquid
- 1 Rainier beer
- 7 oz. canned chipotle peppers in adobo sauce (1 small can)
- 1 - 2 T cocoa powder
- 7 cloves garlic, minced
- Oregano to taste
- Cumin to taste
- Paprika to taste

* Directions

1. Preheat the oven to 350°
2. Dice the bacon, saute it in a stock pot, and remove when cooked. Leave the bacon fat in the pot.
3. While the bacon is cooking, dice two onions and chop the bell peppers. When the bacon is finished, soften the onions in the bacon fat.
4. Blacken the bell peppers in the broiler.
5. Without peeling, cut one onion into fat discs (1/2 inch thick) and place in a cast iron pan. Put the chicken on top of the onion slices and salt it. Roast at 350° for 20 minutes per pound.
6. When the onions are reduced and translucent, add the cooked beans, the canned tomatoes, the blackened bell peppers, the beer, and the minced garlic.
7. Puree the can of chipotle peppers. It helps to thin it with liquid from the pot. Add to the pot and simmer.
8. When the chicken is finished cooking, pull it and add to the chili. (I recommend saving the pan drippings as well as the onion.)
9. As the chili reduces, season with cocoa powder, oregano, cumin, paprika, salt, and black pepper.
10. When the chili is finished reducing, serve over rice. Garnish with bacon, shredded cheese, cilantro, or lime.

