#+HTML_LINK_HOME: ../index.html
#+OPTIONS: toc:nil num:nil H:5 ':t title:t date:nil author:nil ^:nil
#+HTML_HEAD: <link href="../css/solarized-dark.css" rel="stylesheet" />
#+TITLE: Michael Stokley - Resume

#+ATTR_HTML: :align center :border 0 :rules none
| [[mailto:michael@michaelstokley.com][michael@michaelstokley.com]] |   | (303) 801-8575       |   | Seattle, WA               |
| [[http://michaelstokley.com][michaelstokley.com]]         |   | [[https://github.com/mastokley][github.com/mastokley]] |   | [[https://linkedin.com/in/mastokley][linkedin.com/in/mastokley]] |

* Profile
Software developer. I'm patient enough to take difficult projects seriously, and
driven enough to automate tedious, needlessly manual work. In my previous
accounting position, I greatly exceeded expectations by teaching myself SQL and
relational database theory in order to automate data entry / data quality work
(and avoid using a cumbersome GUI). Since then, I have spent two years studying
math, computer science, and statistics at North Seattle College, attended Code
Fellows' Python Development Intensive (taught by esteemed pythonista Cris
Ewing), and have independently studied the classic textbook /The Structure and
Interpretation of Computer Programs/. I've been working as a foundational member
of the engineering team at iDatalabs, building out a customer facing web portal
with Vue.js, Flask, and PostgreSQL. My goals for 2018: learn more diverse
languages (e.g. functional, typed, low-level, or systems); learn to handle
asynchrony without callbacks (e.g. channels found in Go or Clojure); blog about
design patterns; work through a few more chapters of the SICP.

* Technical Skills
** Proficient
Python, Django, Flask, PostgreSQL, JavaScript/HTML/CSS, Vue.js, Git, SQL, Unix,
MVC, HTTP, OOP, FP, Highcharts
** Familiar
Webpack, AWS, Heroku, Ansible, Nginx, Gunicorn, MongoDB, Pyramid, Scheme,
Clojure
* Experience
** iDatalabs, Bellevue, WA
*** Full Stack Engineer, /2017.01 - 2017.10/
I owned (built, maintained, and took full responsibility for) a Vue.js single
page application that displays and sells marketing data; I maintained and
updated the consumed api (written in Flask) and updated underlying db schema to
fit api requirements as needed. I worked on all tiers of the architecture, from
UI to backend, to our Postgres and Mongo databases, to the various Apache and
Nginx servers deployed across Azure instances.
  - Designed and implemented a 'store' to manage client-side shared state using
    Vuex
  - Optimized perceived page performance, including both frontend and backend
    optimizations
  - Knocked up internal admin dashboards in Flask as needed for Sales,
    Marketing, Analytics

** Red Mountain Software, Seattle, WA
*** Freelance Web Developer, /2016.08 - 2016.10/
Designed, built, and tested an internal management application according to
client specification. Thoughtfully designed and implemented db schema to fit
domain-specific business objects. App built with Django and PostgreSQL with
jQuery on the front as needed.

** Sternshus, Seattle, WA
*** Co-founding Full Stack Developer, /2016.07 - 2016.09/
Provided front-end solutions in the context of rapidly changing business
requirements. Worked primarily in Webflow, Django, and MySQL. I am most proud of
having written sed and python scripts to automate merging of Webflow files into
the larger Django project.

** Recology CleanScapes, Seattle, WA
*** AR Specialist, /2012.04 - 2015.04/
Wrote and maintained a library of accurate, sophisticated SQL queries to capture
evolving data inconsistencies; these queries eliminated 37.5 labor hours per
month despite a 126% increase in customer accounts over a two year period

# - Wrote and maintained a library of accurate, sophisticated SQL queries to capture evolving data inconsistencies; these queries eliminated 37.5 labor hours per month despite a 126% increase in customer accounts over a two year period
# - Designed database reports for internal and external customers, such as government officials and senior management
# - Delegated data entry / data revision tasks
# - Collaborated with operations, data quality, payment processing, and customer service teams to analyze and improve processes as new city contracts were won
# - Oversaw and coordinated all billing and collections activities
# - Closed the month on a deadline

* Projects
#+ATTR_HTML: :border 0 :rules none
| 2016.10 | *\quot{}Nord Entities\quot{}*, [[http://michaelstokley.com/Projects/nord-entities][michaelstokley.com/Projects/nord-entities]]                                                            |
|         | Literate programming exploration of natural language processing techniques such as tokenizing, chunking, and named entity recognition. Written in Python with Requests, the NLTK, and Beautiful Soup. |
| 2016.06 | *\quot{}Twitter Haiku\quot{}*, [[http://michaelstokley.com/Projects/twitter-haiku][michaelstokley.com/Projects/twitter-haiku]]                                                                                     |
|         | Literate programming exercise in web scraping, tokenizing, and functional programming techniques learned from the SICP. Written in Python.                                                            |
| 2016.04 | *Toy Domain Scraper*, [[http://michaelstokley.com/Projects/toy-domain-scraper][michaelstokley.com/Projects/toy-domain-scaper]]                                                                                               |
|         | A web scraper built in Python. Uses breadth-first traversal for reliable, fast results.                                                                                                               |

* Education
** Code Fellows, Seattle, WA
*Certificate*, /2016/ \\
Advanced Python development, with emphasis on test driven development, pair
programming, agile methodologies, version control, and basic data structures and
algorithms
** North Seattle College, Seattle, WA
*Coursework*, /2012 - 2014/ \\
Math, Statistics, and Computer Science

** St. John's College, Annapolis, MD
*B. A., Philosophy*, /2009/ \\
Double Major, Philosophy and History of Math and Science \\
Double Minor, Classical Studies and Comparative Literature
