#+HTML_LINK_UP: ../../index.html
#+HTML_LINK_HOME: ../../index.html
#+OPTIONS: toc:nil num:nil H:5
#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry} 
#+LATEX_CLASS_OPTIONS: [a4paper, 10pt, oneside, hidelinks]
* Michael Stokley
| [[mailto:michael@michaelstokley.com][michael@michaelstokley.com]] |   | [[http://www.linkedin.com/in/mastokley][linkedin.com/in/mastokley]] |
| (303) 801-8575             |   | [[http://github.com/mastokley][github.com/mastokley]]      |
| Seattle, WA                |   | [[http://www.michaelstokley.com][michaelstokley.com]]        |
** Profile
Independent, self-motivated individual who places a high value on remaining engaged and challenged. As night shift data entry clerk, I involved myself in as many additional projects as possible, such as video review and 'closing misses'; as AR Specialist, I taught myself intermediate SQL, which permitted me to overhaul our billing and service history reports as well as automate or streamline many data entry / data quality processes. In both positions I greatly exceeded the expectations set by both the stated job description and by my predecessors. I look forward to meeting new challenges, growing as an employee, and contributing in a new position at your organization.
** Technical Skills
*** Proficient
Python, Django, Pyramid, SQL, HTML/CSS, Relational Database Theory, Debian, Bash
*** Familiar
JavaScript, jQuery, AWS Deployment, Heroku Deployment, Ansible, Postgres, Scheme
** Education
*** Code Fellows, Seattle, WA, 2016
Certificate, Advanced Python Development
*** North Seattle College, Seattle, WA, 2012 - 2014
Two years of Math, Statistics, and Computer Science coursework
*** St. John's College, Annapolis, MD, 2009
B. A. in Philosophy
** Projects
*** "Reciprocity", 2016.04
- a recipe sharing and collaboration web app
- source at [[http://github.com/TeamReciprocity/reciprocity][github.com/TeamReciprocity/reciprocity]]; live site at [[http://reciprocity.michaelstokley.com][reciprocity.michaelstokley.com]]
- built with Django and Postgres, deployed via Ansible on an AWS EC2 instance
- < responsibilities and accomplishments >
- < highlight the portions of specifically owned >
*** "HomeQuest", 2016.03
- web app to gamify household chores and chore management
- manually implemented authorization, authentication as well as row-level security
- built with Pyramid and Postgres, deployed on Heroku
- source at [[http://github.com/homequest][github.com/homequest]]; live site at [[http://homequest.michaelstokley.com][homequest.michaelstokley.com]]
*** Learning Journal, 2016.03
- lightweight personal blog with single-user authentication
- built with Pyramid and Postgres, deployed on Heroku
- source at [[http://github.com/mastokley/learning_journal][github.com/mastokley/learning\under{}journal]]; live site at [[http://learning_journal.michaelstokley.com][learning\under{}journal.michaelstokley.com]]
** Experience
*** Recology CleanScapes
**** AR Specialist, 2012.04 - 2015.04
- Oversaw and coordinated all billing and collections activities
- Developed accurate, sophisticated SQL queries to capture evolving data inconsistencies. These queries eliminated ~37.5 hours of labor per month despite a 126% increase in customer accounts over two years
- Designed database reports for internal and external customers, such as government officials and senior management
- Delegated data entry / data revision tasks
- Collaborated with operations, data quality, payment processing, and customer service teams to analyze and improve processes as new city contracts were won
- Closed the month on a deadline
**** Data Quality Specialist, 2011.07 - 2012.04

Various data entry; dispatch and ‘front desk’/customer service duties for graveyard shift; reviewed truck video for misses and accidents; ‘closing’ misses; illegal dumping reporting for SPU; various clerical, reporting, and recordkeeping duties
*** Kojen English Language School in Taipei, Taiwan
**** ESL Teacher, 2009.10 - 2010.10

Taught high energy ESL classes for children aged 5 - 18; resolved classroom conflicts; planned lessons and coordinated lesson plans with co-teachers; prepared end of class student grade reports
